
export const SET_PUZZLE = 'SET_PUZZLE'
export const LOAD_PUZZLE = 'LOAD_PUZZLE'
export const SET_MODE = 'SET_MODE'
export const SET_SELECTED_CELL = 'SET_SELECTED_CELL'
export const SET_CELL_VALUE = 'SET_CELL_VALUE'
export const SET_FLASH_CELL = 'SET_FLASH_CELL'
export const CLEAR_FLASH_CELL = 'CLEAR_FLASH_CELL'