
export const SET_PUZZLE = 'SET_PUZZLE'
export const GET_PUZZLE_SUCCESS = 'GET_PUZZLE_SUCCESS'
export const LOAD_PUZZLE = 'LOAD_PUZZLE'
export const SET_MODE = 'SET_MODE'

export const GET_SELECTED_CELL = 'GET_SELECTED_CELL'
export const SET_SELECTED_CELL = 'SET_SELECTED_CELL'

export const SET_CELL_VALUE = 'SET_CELL_VALUE'